### PR TITLE
Fead: add validation for min/max value

### LINKED ISSUE #13: Update default validate functions for number field
Update default validate functions for number field to include `min` and `max` options.

If number is under min or over max it should trigger validation error.

### PR DESCRIPTION
**Pull request by corners2wall**
Closes #13

### CODE REVIEW

**Comment by corners2wall** [comment]
@Trilmatic  check pls

**Review by Trilmatic — APPROVED** [review]
@corners2wall thank you. Approved. Would you please consider staring this project so we reach out to more people?

**Comment by corners2wall** [comment]
@Trilmatic  What do you mean about "staring this project"

**Comment by Trilmatic** [comment]
@corners2wall i meant giving this project a star

**Comment by corners2wall** [comment]
maybe next time

**Pull request merged**
